<? if (isset($this->artistRow)): ?>
    <? if (!$this->isAjax): ?>
    <div class="container regular">
    <? endif; ?>

    <div class="collection-info">
        <h2><?= ucfirst($this->artistRow->name); ?></h2>
        <div class="embed-image">
            <img src="<?= $this->artistRow->getCover(); ?>"/>
        </div>

        <div class="" style="text-align: justify; min-height: 380px;">
            <?= $this->artistRow->getInfo(); ?>
        </div>
    </div>

    <div class="caption">
    <div class="info">
    <?= $this->t('This page') . ': ' . $this->a($this->artistRow->pageUrl); ?>
    </div>
    </div>

    <?= $this->render('artist/similarity.phtml'); ?>



    <? if (!$this->isAjax): ?>
    </div>
    <? endif; ?>
<? else: ?>
    <p><?= $this->t('Artist not found!'); ?>
<? endif; ?>
