<? if (isset($this->artistRow)): ?>
    <? if (!$this->isAjax): ?>
    <div class="container regular">
    <? endif; ?>

    <div class="collection-info">
        <h2><?= ucfirst($this->artistRow->name); ?></h2>
        <div class="span3">
            <img src="<?= $this->artistRow->getCover(); ?>"/>
        </div>

        <div class="span8" style="text-align: justify">
            <?= $this->artistRow->getInfo(); ?>
        </div>
    </div>

    <?= $this->render('artist/similarity.phtml'); ?>



    <? if (!$this->isAjax): ?>
    </div>
    <? endif; ?>
<? else: ?>
    <p><?= $this->t('Artist not found!'); ?>
<? endif; ?>
