<? if (count($this->artistRow->getTopAlbumList())): ?>
<div class="similarity-list">
    <h2><?= $this->t('Top Albums'); ?></h2>
    <?
        foreach ($this->artistRow->getTopAlbumList() as $albumRow) {
            if ($this->isAjax) {
                echo $this->playlistSquare($albumRow);
            } else {
                echo $this->lightSquare(
                    '/album/' . urlencode($albumRow->artist) . '/' . urlencode($albumRow->name),
                    $albumRow->name,
                    $albumRow->cover
                );
            }
        }
    ?>
</div>
<? endif; ?>;

<? if (count($this->artistRow->getSimilarityList())): ?>
<div class="similarity-list">
    <h2><?= $this->t('Similar Artists'); ?></h2>
    <?
        foreach ($this->artistRow->getSimilarityList() as $artistRow) {
            echo $this->lightSquare(
                '/artist/' . urlencode($artistRow->name),
                $artistRow->name,
                $artistRow->cover,
                $this->isAjax
            );
        }
    ?>
</div>
<? endif; ?>
