<html>
    <head>
        <title>Amuzi :: <?= $this->data->title; ?></title>
        <?= $this->headLink(); ?>
    <head>
    <body>
        <div class="content">
            <h1>Amuzi :: <?= $this->data->title; ?></h1>
            <div class="description"><img src="<?= $this->data->cover; ?>" alt="cover"/> <?
            if ('DbTable_TrackRow' === get_class($this->data)) {
                echo '<p>' . $this->data->title . '</p>';
            } else {
                try {
                    echo $this->trackListHtml($this->data->trackList);
                } catch(Exception $e) {
                    echo $e->getMessage();
                }
            }
?></div>
        </div> <!-- .content -->
        <div id="url"><?= $this->url; ?></div>

        <?= $this->headScript(); ?>
    </body>
</html>
