<h1>AMUZI Documentation</h1>

<h2>Introduction</h2>

AMUZI goals are:

<ol>
<!-- 1 --><li>Being free from head to foot;</li>
<!-- 2 --><li>Users can interact with the system, managing their songs, without stop what is currently plaing;</li>
<!-- 3 --><li>Users can download the songs without ceremony;</li>
<!-- 4 --><li>Have a minimalistic and powerful API to enable access to all it's public content;</li>
</ol>

<!-- TODO: 1 goal -->

<p>For instance, on Youtube, if you are watching a video and wants to search other stuff, the currently playing video will be interrupted. It can't happen with music. Users must be able to interact with the system without messing up what what is currently playing. Despite it may represent big changes on the software architecture it is a fundamental characteristic.</p>

<p>Users can download the songs in MP3 without going through headache of wait X seconds or being tormented by zillions advertisement messages with big blinking download button that are there to distract them. As download the MP3 is a desirable thing, at AMUZI this feature must be at disposal.</p>

<p>Not only users can access the system's content through the user interface provided, they can also build software to interact with AMUZI.</p>



<!-- last on the introduction -->

<p>Not all the features described on this document are implemented. This document aims to keep clear AMUZI's goals and peculiarities. The following sections explains how the main features works.</p>


<h2>Music Objects</h2>


<h3>Music</h3>
The music itself is the simplest object....

<h2>Commands</h2>

<p>In order to enable music objects to be shared it is a good decision to use the fragment part of the url to keep carry that information.</p>

<p>As the commands will be embedded on links outside AMUZI, it must be done so that AMUZI will recognize the wish to add an object.</p>

<p>Clicking on the share links have different effects depending if the user is or not new to AMUZI. For new users it will just show the shared object and allow him to play it. For returning users it will automatically add the object on the user's collection.</p>

<p>To have a better control over the command structure, it will be used IDs instead of the music objects names. This will keep the URLs short.


<h2>Automatically Associates Music with a Youtube Video</h2>

<h2>API</h2>
