<h1>AMUZI Documentation</h1>

<ul id="toc"></ul>

<h2>Introduction</h2>

AMUZI goals are:

<ol>
<!-- 1 --><li>Being free in every way;</li>
<!-- 2 --><li>Users can interact with the system, managing their songs, without stop what is currently playing;</li>
<!-- 3 --><li>Users can download the songs without ceremony;</li>
<!-- 4 --><li>Have a minimalistic and powerful API to enable access to all it's public content;</li>
</ol>

<!-- TODO: 1 goal -->

<p>For instance, on Youtube, if you are watching a video and wants to search other stuff, the currently playing video will be interrupted. It can't happen with music. Users must be able to interact with the system without messing up what what is currently playing. Despite it may represent big changes on the software architecture it is a fundamental characteristic.</p>

<p>Users can download the songs in MP3 without going through headache of wait X seconds or being tormented by zillions advertisement messages with big blinking download button that are there to distract them. As download the MP3 is a desirable thing, at AMUZI this feature must be at disposal.</p>

<p>Not only users can access the system's content through the user interface provided, they can also build software to interact with AMUZI.</p>



<!-- last on the introduction -->

<p>Not all the features described on this document are implemented. This document aims to keep clear AMUZI's goals and peculiarities. The following sections explains how the main features works.</p>


<h2>Music Objects</h2>

There is 4 different music objects:

<ul>
    <li>Track</li>
    <li>Music</li>
    <li>Album</li>
    <li>User's playlist</li>
</ul>

<h3>Track</h3>

<p>Is the simplest of all objects. Is basically composed by an URL that points to the media itself (mp3, ogg and so on). The track can also have a title, a cover image and information about it's duration.</p>

<h3>Music</h3>

<p>A music is like a track but more abstract. While the track is just the media file, the music relates to the artist name and the music title that it represents. The music object is represented by a track.</p>

<h3>Album</h3>

<p>An album is a collection of music objects. For each music disc recorded there is a corresponding album object.</p>

<h3>User's playlist</h3>

<p>While album is a set of music objects, the playlist is a set of tracks. Once a user have added a music to his/her playlist, what is trully added is the track that represents that music. Afterwards, if the music object have a new track to represent it, it won't affect the user's playlist.</p>

<h3>Music</h3>
The music itself is the simplest object....

<h2>Commands</h2>

<p>In order to enable music objects to be shared it is a good decision to use the fragment part of the url to keep carry that information.</p>

<p>As the commands will be embedded on links outside AMUZI, it must be done so that AMUZI will recognize the wish to add an object.</p>

<p>Clicking on the share links have different effects depending if the user is or not new to AMUZI. For new users it will just show the shared object and allow him to play it. For returning users it will automatically add the object on the user's collection.</p>

<p>To have a better control over the command structure, it will be used IDs instead of the music objects names. This will keep the URLs short. The indicate the beginning of the commands, the char "!" will be used. Each music object type will be represented by a different letter:</p>

<ul>
<li>t - Track;</li>
<li>p - Playlist.</li>
</ul>

<p>The ID of each object is an integer. So, the string "p217" would represent the playlist that have ID equals 217. The user who click on a link like http://amuzi.net/#!p217 will only be able to view it's content if the playlist 217 is set to public.</p>



<h2>Automatically Associates Music with a Youtube Video</h2>

<h2>API</h2>
