<h2>Panels</h2>

<p class="text-center"><img src="/img/panel_selector.png" title="Switch panels" class="img-polaroid"/></p>

<p>Switch between panels by clicking on the "search" and "music" icons located at the top center of the page. The search panel is the place to search for tracks and albums while the music panel is where your music is stored.</p>

<p>You can also use the arrow keys &larr; and &rarr; to switch panels.</p>

<h2>Playlists and albums</h2>

<p>Playlists and albums are displayed on the "music" panel.</p>

<p class="text-center"><img src="/img/playlist_album.png" title="Playlists and albums" class="img-polaroid"/></p>

<p>You can play the item by clicking on the play button <img src="/img/play_icon_square.png" class="text-img"/> and you can click on the info button <img src="/img/info_icon.png" class="text-img"/> and get details about the item.</p>

<p>When you add a track from the "search" panel, it goes to the active playlist, which have a red background color. It's not possible to add tracks on albums.</p>

<h2>The player</h2>

<p>Once you  have selected a playlist or album to play, you can use the player.</p>

<p class="text-center"><img src="/img/player.png" class="img-polaroid"/></p>

<p>You can drag and drop the tracks to change the order as well as play, pause, select the music to play and adjust the volume.</p>

<p>Once the cursor is over the track, you'll see the settings button <img src="/img/settings_black.png"/>, click on this button and Amuzi will open a modal where you can perform many action with that track, like assess it's quality, download the video or share it with others.</p>
