

<div class="slidegroup">

    <div class="slide" id="slide-search">
        <div class="container">
            <?= $this->form; ?>
            <div id="result">
            </div>
            <button id="more-results" class="btn"><?= $this->t('More'); ?></button>
        </div>
    </div>

    <div class="slide" id="slide-music-manager">
        <div class="music-manager-group">
            <div class="music-manager" id="transfer"></div>
            <div class="music-manager" id="playlists">
                <h5><?= $this->t("Your playlists"); ?></h5>
                <div class="stripe">
                </div>
            </div>
            <div class="music-manager" id="edit-playlist"></div>
        </div>
        <?= $this->jPlayer(); ?>
    </div>

</div>





<? if(isset($this->userId)): ?>
<div class="invisible" id="userId">
    <?= $this->userId; ?>
</div>




<? endif; ?>
