<div class="slidegroup">

    <div class="slide" id="slide-search">
        <div class="mozaic"></div>
        <div class="container">
            <?= $this->form; ?>
            <div id="result">
                <div id="close-results"><a href="#">x</a></div>
            </div>
            <div id="more-results" class="btn"><?= $this->t('More'); ?></div>
        </div>
    </div>

    <?= $this->render('index/slide-music-manager.phtml'); ?>

</div>

<?= $this->userIdHtml() ?>
