<div class="slidegroup">

    <div class="slide" id="slide-search">
        <div class="mozaic"></div>
        <div class="container">
            <?= $this->form; ?>
            <div id="result">
            </div>
            <button id="more-results" class="btn"><?= $this->t('More'); ?></button>
        </div>
    </div>

    <?= $this->render('index/slide-music-manager.phtml'); ?>

</div>

<?= $this->userIdHtml() ?>
