<div class="container regular">
    <?
    if(isset($this->message))
        echo $this->statusMessage($this->message);
    ?>

    <div class="header container inner-login left">
        <div class="wrap">
            <h4>Amuzi is an open source mashup that combines information from different sources and allow you to search, organize and listen to music</h4>
        </div>

        <div class="wrap quote-set">
            <blockquote class="quote quote-active">
                <p>Amuzi is about the music of the people, by the people, for the people. <img src="/img/Abraham-Lincoln.jpg" class="img-circle quote-person"/></p>
                <small>Abraham Lincoln</small>
            </blockquote>

            <blockquote class="quote">
                <p>Amuzi is a way of life, Amuzi is my way of life, and I aim to keep it. <img src="/img/Homer-Simpson.jpg" class="img-circle quote-person"/></p>
                <small>Homer Simpson</small>
            </blockquote>

            <blockquote class="quote">
                <img src="/img/Linus-Torvalds.jpg" class="img-circle quote-person"/>
                <p>I said talk is cheap, show me code. Then Diogo showed me Amuzi's code and it's beautiful. Now, I can't stop using it.</p>
                <small>Linus Torvalds</small>
            </blockquote>

        </div>
    </div>

    <div class="controls controls-row">
        <div class="span5">
            <a href="#" id="facebook-connect"><img src="/img/facebook-connect.png" alt="Connect using Facebook"/></a>
<?
    if (isset($this->locale) && 'pt_BR' == $this->locale) {
        echo '<br/><br/><iframe width="350" height="263" src="http://www.youtube.com/embed/UGl-sSa5ibI" frameborder="0" allowfullscreen></iframe>';
    }
?>
        </div>
        <div class="span6">
            <?= $this->form; ?>
        </div>

    </div>



</div>
