<div class="container regular">
    <?
    if(isset($this->message))
        echo $this->statusMessage($this->message);
    ?>

    <div class="header container inner-login left">
        <div class="wrap">
            <h4>Amuzi is an open source mashup that combines information from different sources and allow you to search, organize and listen to music</h4>
        </div>

        <div class="wrap quote-set">
            <blockquote class="quote quote-active">
                <img src="/img/Abraham-Lincoln.jpg" class="img-circle quote-person" alt="Abraham Lincoln"/>
                <p>Amuzi is about the music of the people, by the people, for the people.</p>
                <small>Abraham Lincoln</small>
            </blockquote>

            <blockquote class="quote">
                <img src="/img/Homer-Simpson.jpg" class="img-circle quote-person" alt="Homer Simpson"/>
                <p>Amuzi is a way of life, Amuzi is my way of life, and I aim to keep it.</p>
                <small>Homer Simpson</small>
            </blockquote>

            <blockquote class="quote">
                <img src="/img/Linus-Torvalds.jpg" class="img-circle quote-person" alt="Linus Torvalds"/>
                <p>I said talk is cheap, show me code. Then Diogo showed me Amuzi's code and it's beautiful. Now, I can't stop using it.</p>
                <small>Linus Torvalds</small>
            </blockquote>

            <blockquote class="quote">
                <img src="/img/Beyonce.jpg" class="img-circle quote-person" alt="Beyonce"/>
                <p>I like Amuzi and I want to put a ring on it.</p>
                <small>Beyoncé</small>
            </blockquote>
        </div>
    </div>

<? if (isset($this->locale) && 'pt_BR' == $this->locale): ?>
    <div class="intro-video"><a href="/index/introvideo"><img data-content="Assista ao vídeo do projeto" class="img-circle" src="/img/big_play.svg" type="image/svg+xml" alt="Play"/></a></div>
<? endif; ?>

    <div class="row">
        <div class="col-sm-6">
            <a href="#" id="facebook-connect"><img src="/img/facebook_connect.png" alt="Connect using Facebook"/></a>
        </div>
        <div class="col-sm-6">
            <?= $this->form; ?>
        </div>

    </div> <!-- row -->

    <div class="row">
        <div class="col-sm-6"></div>
        <div class="col-sm-6">
            <div class="col-sm-6">
                <?= $this->a('/Auth/index/forgotpassword', $this->t('Forgot password')); ?>
            </div>
            <div class="col-sm-6">
                <?= $this->a('/Auth/index/register', $this->t('Register')); ?>
            </div>
        </div>
    </div>

    <div class="row row-lg-height">
        <div class="col-sm-12">
            <p>This is an open source project. All the code is available on
                <a href="https://github.com/dmelo/amuzi">GitHub</a>.</p>
        </div>
    </div>



</div>
