<div class="slide" id="slide-music-manager">
    <div class="music-manager-group">
        <div class="music-manager" id="transfer"></div>
        <div class="music-manager" id="playlists">
            <h5><?= $this->t("Your playlists"); ?></h5>
            <div class="stripe">
            </div>
        </div>
        <div class="music-manager" id="edit-playlist"></div>
    </div>
    <?= $this->jPlayer(); ?>
</div>

