<div class="container regular">
    <?
    if(isset($this->message))
        echo $this->statusMessage($this->message);
    ?>

    <div class="controls controls-row">
        <div class="span5">
            <a href="#" id="facebook-connect"><img src="/img/facebook-connect.png" alt="Connect using Facebook"/></a>
        </div>
        <div class="span6">
            <?= $this->form; ?>
            <?= $this->render('index/login-complement.phtml'); ?>
        </div>

    </div>


</div>
