<?= $this->form; ?>

<table id="playlistsettings-result">
    <thead>
        <tr class="topic">
            <th>--</th>
            <th><?= $this->t('Name'); ?></th>
            <th><?= $this->t('Nr Tracks'); ?></th>
            <th><?= $this->t('Public'); ?></th>
        </tr>
    </thead>
    <tbody>
        <?= $this->partial('/playlist/search.phtml', array('resultSet' => $this->resultSet, 'formEdit' => $this->formEdit)); ?>
    </tbody>
</table>
