<? if (!$this->isAjax): ?>
<div class="container regular">
    <div id="load-playlist" isAlbum="<?= 'album' === $this->collection->getType() ? 'true' : 'false'; ?>" class="invisible"><?= $this->collection->id; ?></div>
    <?= $this->jPlayer('lonely'); ?>

<? endif; ?>

<div class="collection-info">
    <div class="cover">
        <img src="<?= $this->collection->getCover(); ?>"/>
    </div>
    <div class="caption">
        <?
            $data = array();
            if ('album' === $this->collection->getType()) {
                $data['Artist'] = $this->isAjax ? ucfirst($this->collection->artist) : $this->a('/artist/' . urlencode($this->collection->artist), ucfirst($this->collection->artist));
            }

            $data['Name'] = $this->collection->getCoverName();
            $data['Type'] = $this->t(ucfirst($this->collection->getType()));
            $data['Duration'] = $this->secsToTime($this->collection->playTime());
            $data['Nro Tracks'] = count($this->collection->getTrackListAsArray());

            if ($this->collection instanceof DbTable_AlbumRow) {
                $data['Share'] = $this->a($this->collection->facebookUrl, '<img class="icon" src="/img/facebook.png"/>')
                    . $this->a($this->collection->shareUrl, '<img class="icon" src="/img/link.png"/>');
            }

        ?>

        <? foreach ($data as $key => $value): ?>
            <div class="info">
                <?= $this->t($key) . ': ' . $value; ?>
            </div>
        <? endforeach; ?>

    </div>
    <table class="tracklist table table-striped">
        <caption><?= $this->t('Track list'); ?></caption>
        <thead></thead>
        <tbody>
        <? $count = 0; foreach ($this->collection->getTrackListSync() as $track): ?>
            <? if (!array_key_exists('title', $track)) continue; ?>
            <tr>
                <td><?= ++$count; ?></div>
                <td><img src="<?= $track['cover']; ?>"/></td>
                <td>
                    <div class="info"><?=  $this->t('Name') . ': ' . $track['title']; ?></div>
                    <div class="info"><?= $this->t('Duration') . ': ' . $this->secsToTime($track['duration']); ?></div>
                </td>
            </tr>
        <? endforeach; ?>
        </tbody>
    </table>


</div>

<?= $this->render('artist/similarity.phtml'); ?>

