<? if (!$this->isAjax): ?>
<div class="container regular">
    <?= $this->jPlayer('lonely'); ?>
<? endif; ?>

<div class="collection-info">
    <div class="cover">
        <img src="<?= $this->collection->getCover(); ?>"/>
    </div>
    <div class="caption">
        <div class="info">
            <?= $this->t('Name') . ': ' . $this->collection->getCoverName(); ?>
        </div>
        <div class="info">
            <?= $this->t('Type') . ': ' . $this->t(ucfirst($this->collection->getType())); ?>
        </div>
        <div class="info">
            <?= $this->t('Duration') . ': ' . $this->secsToTime($this->collection->playTime()); ?>
        </div>
        <div class="info">
            <?= $this->t('Nro Tracks') . ': ' . count($this->collection->getTrackListAsArray()); ?>
        </div>
        <? if ($this->collection instanceof DbTable_AlbumRow): ?>
            <div class="info">
                <?= $this->t('Share') . ': ' . '<a href="' . $this->collection->facebookUrl . '"><img class="icon" src="/img/facebook.png"/></a>'
                . '<a href="' . $this->collection->shareUrl . '"><img class="icon" src="/img/link.png"/></a>' ; ?>
            </div>
        <? endif; ?>

    </div>
    <table class="tracklist table table-striped">
        <caption><?= $this->t('Track list'); ?></caption>
        <thead></thead>
        <tbody>
        <? $count = 0; foreach ($this->collection->getTrackListAsArray() as $track): ?>
            <? if (!array_key_exists('title', $track)) continue; ?>
            <tr>
                <td><?= ++$count; ?></div>
                <td><img src="<?= $track['cover']; ?>"/></td>
                <td>
                    <div class="info"><?=  $this->t('Name') . ': ' . $track['title']; ?></div>
                    <div class="info"><?= $this->t('Duration') . ': ' . $this->secsToTime($track['duration']); ?></div>
                </td>
            </tr>
        <? endforeach; ?>
        </tbody>
    </table>
</div>

<? if (!$this->isAjax): ?>
</div>
<? endif; ?>

