<? if(isset($this->resultSet)): ?>
    <? foreach($this->resultSet as $row): ?>
    <tr class="load">
        <td><img alt="Cover image" alt="<?= $row->name; ?>" src="<?= $row->getCover(); ?>"/></td>
        <td class="name"><?= $row->name; ?></td>
        <td><?= $row->countTracks(); ?></td>
        <td><input type="checkbox" name="public" class="public" <?= $row->privacy === 'public' ? 'checked="checked"' : ''; ?> /></td>
    </tr>
    <? endforeach; ?>
<? else: ?>
<?= $this->error(); ?>
<? endif; ?>
