<?= $this->doctype(); ?><html>
    <head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
        <?= $this->headTitle(); ?>
        <?= $this->headMeta(); ?>
        <?= $this->headLink(); ?>

    </head>

    <body>
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="brand" href="/">Amuzi</a>
            <ul class="nav">
                <li class="dropdown">
                    <a href="#" class="loginRequired dropdown-toggle" data-toggle="dropdown" title="Playlist Manager"><?= $this->t('Playlist'); ?> <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="/playlist/new" class="loadModal loginRequired noForm" name="newPlaylist" title="<?= $this->t('Create'); ?>"><?= $this->t('Create'); ?></a></li>
                        <li><a href="/playlist" class="loadModal loginRequired noForm" name="playlist" title="<?= $this->t('List'); ?>"><?= $this->t('List'); ?></a></li>
                        <li><a href="/playlist/remove" class="loadModal loginRequired noForm" name="delPlaylist" title="<?= $this->t('Remove'); ?>"><?= $this->t('Remove'); ?></a></li>
                    </ul>
                </li>
                <li><a href="/user" class="loadModal loginRequired" title="User Settings" id="userSettings"><?= $this->t('Settings'); ?></a></li>
                <li><a href="/docs" title="Docs" target="_blank"><?= $this->t("Docs"); ?></a></li>
                <li><a href="/index/about" class="loadModal" title="About Amuzi"><?= $this->t('About'); ?></a></li>
                <li><div class="loginRequired screens"><div class="screen" id="screen-search"></div><div class="screen" id="screen-music"></div></div></li>
            </ul>
            <div class="pull-right">
                <ul class="nav">
                    <li><a class="loginRequired" href="/Auth/index/logout"><?= $this->t('Logout'); ?></a></li>
                </ul>
            </div>
        </div>
    </div>
</div>

<!-- Github badge -->
  <div class="ribbon">
    <a href="https://github.com/dmelo/amuzi" target="_blank">Fork me on GitHub</a>
  </div>

<div id="wrapper">

    <div id="logo">
        <h2><a href="#"><?= $this->t('amazingly free'); ?></a></h2>
    </div>

    <div class="alert visibility" data-alert="true">
        <a href="#" class="close">&times;</a>
        <p>#</p>
    </div>

    <div id="domain" style="display:none"><?= Zend_Registry::get('domain'); ?></div>

    <div id="user" style="visibility: hidden">
        <img id="image"/>
        <div id="name"></div>
    </div>






    <section id="content">
        <?= $this->layout()->content; ?>
    </section>

</div>

<footer class="footer">
    <div class="container">
        <p id="legal">Copyright &copy; 2011-<?= date('Y'); ?> <a target="_blank" href="http://diogomelo.net">Diogo Oliveira de Melo</a>.</p>
    </div>
</footer>
<!-- end div#footer -->

<!-- Google analytics -->
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-7893542-8']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

        <?= $this->headScript(); ?>

    </body>

</html>
