<?= $this->doctype(); ?>
<html>
    <head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
        <?= $this->headTitle(); ?>
        <?= $this->headMeta(); ?>
        <?= $this->headLink(); ?>

    </head>

    <body>
<div id="fb-root"></div>
<script src="http://connect.facebook.net/en_US/all.js">
</script>
<script>
     FB.init({ 
        appId:'209056955830996', cookie:true, 
        status:true, xfbml:true 
     });

    FB.api('/me', function(user) {
       if(user != null) {
          var image = document.getElementById('image');
          image.src = 'http://graph.facebook.com/' + user.id + '/picture';
          var name = document.getElementById('name');
          name.innerHTML = user.name;
          document.getElementsByTagName('fb:login-button')[0].style.visibility = 'hidden';
       }
       else {
           document.getElementById('user').style.visibility = 'hidden';
       }
     });

</script>

<div id="wrapper">
<div id="header">
    <div class="message">
        <img src="/img/loading.gif"/>
        <div></div>
    </div>

	<div id="logo">
		<h1><a href="#">You2Better </a></h1>
		<h2><a href="#">The music version of Youtube</a></h2>
	</div>
	<!-- end div#logo -->
	<div id="menu">
		<ul>
			<li class="active"><a href="/">Home</a></li>
			<li><a href="/index/api">API</a></li>
			<li><a href="/index/about">About</a></li>
		</ul>
        <div id="user" style="visibility: visible">
            <img id="image"/>
            <div id="name"></div>
        </div>

	</div>
	<!-- end div#menu -->
</div>

      <fb:login-button perms="email,user_checkins" style="visibility: visible">
         Login with Facebook
      </fb:login-button>


<div>
	<div id="page">
		<div id="page-bgtop">
			<div id="content">
				<div class="post">
					<div class="post-bgtop">
						<div class="post-bgbtm">
                            <?= $this->layout()->content; ?>
						</div>
					</div>
				</div>
			</div>
			<!-- end div#content -->
			<div style="clear: both; height: 1px"></div>
		</div>
	</div>
	<!-- end div#page -->
</div>
<!-- end div#wrapper -->
<div id="footer-wrapper">
	<div id="footer">
		<p id="legal">Copyright &copy; 2011 <a href="http://diogomelo.net">Diogo Oliveira de Melo</a> . Designed by <a href="http://www.freecsstemplates.org/">Free CSS Templates</a>.</p>
	</div>
</div>
<!-- end div#footer -->

        <?= $this->headScript(); ?>

    </body>

</html>
