<?= $this->doctype(); ?>
<html>
    <head>
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
        <?= $this->headTitle(); ?>
        <?= $this->headMeta(); ?>
        <?= $this->headLink(); ?>
        <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
        <meta name="description" content="AMUZI - Free online music" />
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

    </head>

    <body>


<div id="fb-root"></div>
<script>
  // Additional JS functions here
    window.fbAsyncInit = function() {
        FB.init({
            appId      : '<?= $this->facebookId; ?>', // App ID
            channelUrl : '<?= $this->facebookChannel; ?>', // Channel File
            status     : true, // check login status
            cookie     : true, // enable cookies to allow the server to access the session
            xfbml      : true,  // parse XFBML
            perms      : 'email'
        });

        // Additional init code here
    };


    // Load the SDK Asynchronously
    (function(d){
        var js, id = 'facebook-jssdk', ref = d.getElementsByTagName('script')[0];
        if (d.getElementById(id)) {return;}
        js = d.createElement('script'); js.id = id; js.async = true;
        js.src = "//connect.facebook.net/en_US/all.js";
        ref.parentNode.insertBefore(js, ref);
    }(document));
</script>

<!--
<div class="navbar navbar-fixed-top" role="navigation">
    <div class="container-fluid">
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand" href="/">Amuzi</a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <form class="navbar-search navbar-form search navbar-left search-loggedoff form-search search-loggedoff" action="/" method="get" role="search">
                        <div class="input-group input-group">
                            <div class=" col-lg-9" >
                            <input type="search" class="search-query form-control" placeholder="Search" name="q" id="q" />
                            </div>
                        </div>
                        <input type="hidden" name="artist" id="artist" />
                        <input type="hidden" name="musicTitle" id="musicTitle" />
                        <input type="hidden" name="type" id="type" />

                    </form>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    <li class="loginRequired"><a href="/user" class="loadModal loginRequired" id="userSettings"><?= $this->t('Settings'); ?></a></li>
                    <li class="loginRequired"><a href="/feedback" class="loadModal loginRequired" id="feedback"><?= $this->t("Feedback"); ?></a></li>
                    <li class="logoffRequired" id="login-button-menu"><a href="/"><?= $this->t("Login"); ?></a></li>
                    <li><a href="/docs" target="_blank"><?= $this->t("Docs"); ?></a></li>
                    <li><a href="/index/help" class="loadModal" ><?= $this->t('Help'); ?></a></li>
                    <li><a href="/index/about" class="loadModal" ><?= $this->t('About'); ?></a></li>
                    <li class="loginRequired"><div class="screens"><div class="screen dark" id="screen-music">&nbsp;</div><div class="screen light" id="screen-search">&nbsp;</div></div></li>
                    <li class="loginRequired"><a id="userEmail" class="loginRequired" href="#"></a></li>
                    <li class="loginRequired"><a class="loginRequired" href="/Auth/index/logout"><?= $this->t('Logout'); ?></a></li>
                </ul>

            </div>
        </div>
    </div>
</div>

-->

<nav class="navbar navbar-default" role="navigation">
    <div class="container">
        <!-- Brand -->
        <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
            <a class="navbar-brand" href="/">AMUZI</a>
        </div>

        <!-- Search -->
        <div class="collapse navbar-collapse">
            <form class="navbar-search search navbar-form navbar-left" action="/" method="get" role="search">
                <input type="search" class="search-query form-control" name="q" id="q" class="form-control"/>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li class="logoffRequired" id="login-button-menu"><a href="/"><?= $this->t("Login"); ?></a></li>
                <li><a href="/docs" target="_blank"><?= $this->t("Docs"); ?></a></li>
                <li><a href="/index/help" class="loadModal" ><?= $this->t('Help'); ?></a></li>
                <li><a href="/index/about" class="loadModal" ><?= $this->t('About'); ?></a></li>
                <li class="loginRequired"><div class="screens"><div class="screen dark" id="screen-music">&nbsp;</div><div class="screen light" id="screen-search">&nbsp;</div></div></li>
                <li class="loginRequired"><a id="userEmail" class="loginRequired" href="#"></a></li>
                <li class="loginRequired"><a class="loginRequired" href="/Auth/index/logout"><?= $this->t('Logout'); ?></a></li>

            </ul>
        </div>
    </div>
</nav>

<!-- Github badge -->
  <div class="ribbon">
    <a href="https://github.com/dmelo/amuzi" target="_blank">Fork me on GitHub</a>
  </div>

<div class="alert visibility" data-alert="true">
    <a href="#" class="close">&times;</a>
    <p>#</p>
</div>


<div id="wrapper">

    <div id="logo">
    </div>


    <div id="domain" style="display:none"><?= Zend_Registry::get('domain'); ?></div>

    <section id="content">
        <?= $this->layout()->content; ?>
    </section>

</div>

<div class="footer">
    <div class="container">
        <p id="legal">Copyright &copy; 2011-<?= date('Y'); ?> <a target="_blank" href="http://diogomelo.net">Diogo Oliveira de Melo</a>.</p>
    </div>
</div>
<!-- end div#footer -->

<? if ('production' === APPLICATION_ENV): ?>
<!-- Google analytics -->
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-7893542-8']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
<? endif; ?>

        <?= $this->headScript(); ?>
 
<? 

try {
    $locale = Zend_Registry::get('locale');
} catch (Zend_Exception $e) {
}

if (isset($locale)): ?>
    <div id="locale" class="invisible"><?= $locale; ?></div>
<? endif; ?>

    </body>

</html>
