drop database youbetter;
create database youbetter;
use youbetter;
source create.sql;
source triggers.sql;
source update0.sql;
source update1.sql;
source update2.sql;
source update3.sql;
source update4.sql;
source update5.sql;
source populate.sql;
